In [1]:
import pandas as pd
df = pd.read_csv("empDataSet.csv")

df.isnull()
df.isna()
df.isnull().sum()
df.dropna()
df.fillna("nan")
clean_df = df.copy()
salary_mean = clean_df["salary"].mean()
clean_df["salary"] = clean_df["salary"].fillna(salary_mean)
clean_df

   employee_id     name department   salary
0          101    Alice         HR  55000.0
1          102      Bob         IT  62000.0
2          103  Charlie        NaN  58000.0
3          104    David    Finance  62125.0
4          105      NaN         IT  71000.0
5          106    Frank         HR  54000.0
6          107    Grace        NaN  62125.0
7          108    Helen  Marketing  65000.0
8          109      Ian    Finance  60000.0
9          110    Jenny        NaN  72000.0

In [2]:
# handel duplicate
df.duplicated()
#df.drop_duplicates()

#handel datatype 
df.dtypes
clean_df["salary"]= clean_df["salary"].astype("int64") 
clean_df

#handel string
df["Name"].str.upper()
df["Name"].str.split("l")
df["department"].str.contains("IT")

KeyError: 'Name'

In [ ]:
#transforming the data
# df.rename(columns={"name":"Name"})
# df = df.rename(columns={"Name":"name"})
s = pd.Series([10,20,"hello"])
df.describe()
df.info()
df.nunique()
df.columns
df.loc[0,["name","salary"]]
df.query("salary > 70000")
df ["name"] = df["name"].fillna("User")

In [1]:
df["salary"].isnull().sum()
df["salary"].sort_values(ascending=False)
df[["employee_id","name","salary","department"]]

NameError: name 'df' is not defined

In [ ]:
df2 = df.copy()
df2.drop_duplicates()
df2["department"]=df2["department"].fillna("Non-tech")
mean_sal = df2["salary"].mean()
print(mean_sal)
df2["salary"] = df2["salary"].fillna(mean_sal)
df2.to_csv("Filtered.csv")

In [14]:
df3 = df.copy()
df3["Tax"] = df3["salary"].apply( lambda x: "20%" if x>=50000 else "10%")

df3.assign(new_salary = df3["salary"]*1.1)
df3 = df3.assign(Gender = "Male")

gender = {"Male" : "M","Female":"F"}
df3["Gender"]=df3["Gender"].map(gender)

In [23]:
df3.groupby("department")["salary"].min()
df3.groupby("department")["salary"].agg(avg_mean="mean",max_val="max")
df3.groupby("department")["salary"].agg(["mean","max","min"])

               mean      max      min
department
Finance     60000.0  60000.0  60000.0
HR          54500.0  55000.0  54000.0
IT          66500.0  71000.0  62000.0
Marketing   65000.0  65000.0  65000.0

In [17]:
df3

   employee_id     name department   salary  Tax Gender
0          101    Alice         HR  55000.0  20%      M
1          102      Bob         IT  62000.0  20%      M
2          103  Charlie        NaN  58000.0  20%      M
3          104    David    Finance      NaN  10%      M
4          105      NaN         IT  71000.0  20%      M
5          106    Frank         HR  54000.0  20%      M
6          107    Grace        NaN      NaN  10%      M
7          108    Helen  Marketing  65000.0  20%      M
8          109      Ian    Finance  60000.0  20%      M
9          110    Jenny        NaN  72000.0  20%      M

In [5]:
print("hyuhujii")

hyuhujii